---
- name: Reboot both hosts and notify
  hosts: all
  become: yes
  vars:
          gmail_app_password: "yaweroxapnroyivb"
  tasks:

    - name: Reboot the host
      ansible.builtin.reboot:
        reboot_timeout: 300
        test_command: whoami

  post_tasks:
    - name: Send email notification
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: "raviranjankumar748@gmail.com"
        password: "{{ gmail_app_password }}"
        to: "raviranjankumar784@gmail.com"
        subject: "Ansible Notification: Hosts Rebooted"
        body: |
          All targeted hosts have been successfully rebooted by Ansible.
        secure: starttls
      delegate_to: localhost
      #run_once: true
